<?php
/**
 * Acf fields for Drum plugin
 * Date: updated 8/16/18
 */


if (function_exists('acf_add_local_field_group')) :

	acf_add_local_field_group(array(
	'key' => 'group_58f7a4dff04c7',
	'title' => 'Admin Dashboard',
	'fields' => array(
		array(
			'key' => 'field_58f7a4e0056d2',
			'label' => 'Allowed User',
			'name' => 'allowed_user',
			'type' => 'user',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'role' => '',
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'array',
		),
		array(
			'key' => 'field_58f7a4e0056ea',
			'label' => 'Show Welcome Screen',
			'name' => 'show_welcome_screen',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33.33333333',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui' => 1,
			'ui_on_text' => 'Show',
			'ui_off_text' => 'Hide',
		),
		array(
			'key' => 'field_58f7a4e0056fc',
			'label' => 'Show Video Tutorials',
			'name' => 'show_video_tutorials',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33.33333333',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'Show',
			'ui_off_text' => 'Hide',
		),
		array(
			'key' => 'field_58f7a4e005708',
			'label' => 'Show Ads',
			'name' => 'show_drum_hosting_ad',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33.33333333',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'Show',
			'ui_off_text' => 'Hide',
		),
		array(
			'key' => 'field_58f7a4e005719',
			'label' => 'Welcome Screen',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_58f7a4e0056ea',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_58f7a4e005725',
			'label' => 'Admin Intro Content',
			'name' => 'admin_intro_content',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_58f7a4e0056ea',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array(
			'key' => 'field_58f7a4e005735',
			'label' => 'Maintenance Hours',
			'name' => 'maintenance_hours',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_58f7a4e0056ea',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '33.3333',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_58f7a4e005741',
			'label' => 'Hosting',
			'name' => 'hosting',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_58f7a4e0056ea',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '33.3333',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_592d967b10cc3',
			'label' => 'Account Manager',
			'name' => 'account_manager',
			'type' => 'select',
			'instructions' => 'Account Manager 1 is always Joe LaPenna',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33.3333',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				0 => 'Account Manager 1',
				1 => 'Account Manager 2',
				2 => 'Account Manager 3',
				3 => 'Account Manager 4',
				4 => 'Account Manager 5',
			),
			'default_value' => array(),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_58f7a4e005751',
			'label' => 'Video Tutorial',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_58f7a4e0056fc',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_58f7a4e005761',
			'label' => 'Video Admin Intro Content',
			'name' => 'video_admin_intro_content',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_58f7a4e0056fc',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array(
			'key' => 'field_58f7a4e005771',
			'label' => 'Videos',
			'name' => 'videos',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_58f7a4e0056fc',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_59e909f45d75f',
					'label' => 'Video Type',
					'name' => 'video_type',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_58f7a4e0056ea',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'Youtube' => 'Youtube',
						'Vimeo' => 'Vimeo',
						'Loom' => 'Loom',
					),
					'default_value' => array(),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array(
					'key' => 'field_58f7a4e028483',
					'label' => 'Vimeo Video ID',
					'name' => 'video_id',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_59e909f45d75f',
								'operator' => '==',
								'value' => 'Vimeo',
							),
							array(
								'field' => 'field_59e909f45d75f',
								'operator' => '!=',
								'value' => 'Loom',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_59e90a695d760',
					'label' => 'Loom Video Embed URL',
					'name' => 'loom_video_url',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_59e909f45d75f',
								'operator' => '==',
								'value' => 'Loom',
							),
							array(
								'field' => 'field_59e909f45d75f',
								'operator' => '!=',
								'value' => 'Vimeo',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_59ea0e4beb56e',
					'label' => 'Loom Video Title',
					'name' => 'loom_video_title',
					'type' => 'text',
					'instructions' => 'Limited 20 characters.',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_59e909f45d75f',
								'operator' => '==',
								'value' => 'Loom',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => 20,
				),
				array(
					'key' => 'field_5b75b4bf638b5',
					'label' => 'Youtube',
					'name' => 'youtube',
					'type' => 'oembed',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_59e909f45d75f',
								'operator' => '==',
								'value' => 'Youtube',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'width' => '',
					'height' => '',
				),
				array(
					'key' => 'field_5b75c2e773c2f',
					'label' => 'Youtube Video Title',
					'name' => 'youtube_video_title',
					'type' => 'text',
					'instructions' => 'Limited 20 characters.',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_59e909f45d75f',
								'operator' => '==',
								'value' => 'Youtube',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => 20,
				),
			),
		),
		array(
			'key' => 'field_58f7a4e00577d',
			'label' => 'Drum Ad',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_58f7a4e005708',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_58f7a4e005788',
			'label' => 'Drum Ad',
			'name' => 'drum_ad',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Ad Hosting' => 'Ad Hosting',
				'Ad SEO' => 'Ad SEO',
				'Ad Maintenance' => 'Ad Maintenance',
			),
			'default_value' => array(),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'admin-dashboard',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;